[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
serde = { version = "1.0", features = ["derive"] }
# serde = "1.0" 
toml = "0.5"
